namespace: grocerylist
connectionstrings:
  postgres: "Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=7f31ff77-9e6b-4981-8e4d-8f93c2f35cfb;"
postgres:
  database: "postgres"
  username: "postgres"
  password: "7f31ff77-9e6b-4981-8e4d-8f93c2f35cfb"